### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by juangustavvo** [ogunjobiFX/MT4-Forex-Signal-Copier-Telegram-Bot#7]
There was an issue 😕

Error Message:
Trade is disabled

**Comment by ogunjobiFX** [comment]
@juangustavvo could you be more descriptive with the trade that you entered and the broker that you may be using? It's likely an internal issue.

**Comment by juangustavvo** [comment]
Hello, I am here using exness broker and I use cent currency, and can be called USC. the problem is in the picture . thank you admin may god bless you 

![Screenshot_2023-07-11-08-06-35-905_org telegram messenger](https://github.com/ogunjobiFX/MT4-MT5-Forex-Signal-Copier-Telegram-Bot/assets/23358095/cf3b60cd-7534-4842-80ed-41ea08678017)
![Screenshot_2023-07-11-08-07-54-084_com android chrome](https://github.com/ogunjobiFX/MT4-MT5-Forex-Signal-Copier-Telegram-Bot/assets/23358095/c1634434-4488-4dc2-8c0d-7df8ae391cfb)
![Screenshot_2023-07-11-08-07-57-711_com android chrome](https://github.com/ogunjobiFX/MT4-MT5-Forex-Signal-Copier-Telegram-Bot/assets/23358095/d57cc3a6-37c6-4e63-af9b-437f7ed55bfe)
![Screenshot_2023-07-11-08-08-03-447_com android chrome](https://github.com/ogunjobiFX/MT4-MT5-Forex-Signal-Copier-Telegram-Bot/assets/23358095/8953aeb9-74ff-4375-8358-a6cc98558e4d)

**Comment by ogunjobiFX** [comment]
The issue is with your broker. If you look here: https://metaapi.cloud/docs/client/models/metatraderTradeResponse/
It looks like you're getting a TRADE_RETCODE_TRADE_DISABLED error. This means that you broker has disabled entering the trade via an API. In an instance like this, my only suggestions are that you either reach out to your broker to ask for the effective permissions to do so or try it using a new broker. Good luck.

**Comment by juangustavvo** [comment]
okay I got the answer. and thank you for the response 👍👍

**Comment by ogunjobiFX** [comment]
@juangustavvo I recommend that you also check out the latest version of the bot here: https://youtu.be/niWDWnlc3xU
